/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface TestInterface extends utils.Interface {
  functions: {
    "findNumInArr(uint256[],uint256)": FunctionFragment;
    "getMaxUsingMathLib(uint256,uint256)": FunctionFragment;
    "getMinUsingMathLib(uint256,uint256)": FunctionFragment;
    "getStorageArr()": FunctionFragment;
    "peekFirstItem(uint256[])": FunctionFragment;
    "viewAddressLib()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "findNumInArr"
      | "getMaxUsingMathLib"
      | "getMinUsingMathLib"
      | "getStorageArr"
      | "peekFirstItem"
      | "viewAddressLib"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "findNumInArr",
    values: [PromiseOrValue<BigNumberish>[], PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getMaxUsingMathLib",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getMinUsingMathLib",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getStorageArr",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "peekFirstItem",
    values: [PromiseOrValue<BigNumberish>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "viewAddressLib",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "findNumInArr",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMaxUsingMathLib",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMinUsingMathLib",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStorageArr",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "peekFirstItem",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "viewAddressLib",
    data: BytesLike
  ): Result;

  events: {};
}

export interface Test extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: TestInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    findNumInArr(
      _arr: PromiseOrValue<BigNumberish>[],
      _target: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getMaxUsingMathLib(
      _a: PromiseOrValue<BigNumberish>,
      _b: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getMinUsingMathLib(
      _a: PromiseOrValue<BigNumberish>,
      _b: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getStorageArr(overrides?: CallOverrides): Promise<[BigNumber[]]>;

    peekFirstItem(
      _arr: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    viewAddressLib(overrides?: CallOverrides): Promise<[string]>;
  };

  findNumInArr(
    _arr: PromiseOrValue<BigNumberish>[],
    _target: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getMaxUsingMathLib(
    _a: PromiseOrValue<BigNumberish>,
    _b: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getMinUsingMathLib(
    _a: PromiseOrValue<BigNumberish>,
    _b: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getStorageArr(overrides?: CallOverrides): Promise<BigNumber[]>;

  peekFirstItem(
    _arr: PromiseOrValue<BigNumberish>[],
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  viewAddressLib(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    findNumInArr(
      _arr: PromiseOrValue<BigNumberish>[],
      _target: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMaxUsingMathLib(
      _a: PromiseOrValue<BigNumberish>,
      _b: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMinUsingMathLib(
      _a: PromiseOrValue<BigNumberish>,
      _b: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getStorageArr(overrides?: CallOverrides): Promise<BigNumber[]>;

    peekFirstItem(
      _arr: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    viewAddressLib(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    findNumInArr(
      _arr: PromiseOrValue<BigNumberish>[],
      _target: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMaxUsingMathLib(
      _a: PromiseOrValue<BigNumberish>,
      _b: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMinUsingMathLib(
      _a: PromiseOrValue<BigNumberish>,
      _b: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getStorageArr(overrides?: CallOverrides): Promise<BigNumber>;

    peekFirstItem(
      _arr: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    viewAddressLib(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    findNumInArr(
      _arr: PromiseOrValue<BigNumberish>[],
      _target: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMaxUsingMathLib(
      _a: PromiseOrValue<BigNumberish>,
      _b: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMinUsingMathLib(
      _a: PromiseOrValue<BigNumberish>,
      _b: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getStorageArr(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    peekFirstItem(
      _arr: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    viewAddressLib(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
